"""Criação inicial

Revision ID: b3baf96267aa
Revises: 
Create Date: 2025-12-01 16:47:23.758002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3baf96267aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('matricula', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('predio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predio_id'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=128), nullable=False),
    sa.Column('nome_equipamento', sa.String(length=100), nullable=False),
    sa.Column('qr_code_path', sa.String(length=256), nullable=True),
    sa.Column('status_atual', sa.String(length=50), nullable=False),
    sa.Column('localizacao_atual_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_cadastro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['localizacao_atual_id'], ['sala.id'], ),
    sa.ForeignKeyConstraint(['responsavel_cadastro_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('historico_checkpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.String(length=50), nullable=False),
    sa.Column('status_novo', sa.String(length=50), nullable=False),
    sa.Column('predio_destino_id', sa.Integer(), nullable=True),
    sa.Column('sala_destino_id', sa.Integer(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('responsavel_alteracao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['predio_destino_id'], ['predio.id'], ),
    sa.ForeignKeyConstraint(['responsavel_alteracao_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sala_destino_id'], ['sala.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_checkpoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_checkpoint_data_alteracao'), ['data_alteracao'], unique=False)

    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=256), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_alvo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['usuario_alvo_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao')
    with op.batch_alter_table('historico_checkpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_checkpoint_data_alteracao'))

    op.drop_table('historico_checkpoint')
    op.drop_table('equipamento')
    op.drop_table('sala')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('predio')
    # ### end Alembic commands ###
